name: "Build release"

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    name: "Build docker image"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - name: Semantic versioning
        id: semver
        uses: paulhatch/semantic-version@v5.3.0
        with:
          change_path: "src"
      - name: Build DOTelL Docker image
        run: docker build . --file src/DOTelL.Api/Dockerfile --tag dotell:${{ steps.semver.outputs.major }}.${{ steps.semver.outputs.minor }}.${{ steps.semver.outputs.patch }}
