name: "Build release"

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:
    name: "Build docker image"
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      
      - name: Log in to the Container registry
        uses: docker/login-actionv3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Semantic versioning
        id: semver
        uses: paulhatch/semantic-version@v5.3.0
        with:
          change_path: "src"

      - name: Build and push DOTelL Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          file: src/DOTelL.Api/Dockerfile
          tags: ${{ env.IMAGE_NAME }}:${{ steps.semver.outputs.major }}.${{ steps.semver.outputs.minor }}.${{ steps.semver.outputs.patch }}
